### ISSUE TITLE
Existing spaces tab is not working

### ISSUE THREAD

**Issue by VCasecnikovs** [tjschulz2/sf-housing-app#34] opened 2023-11-14 03:04 UTC
When I open "existing" tab I do see only white screen

https://github.com/tjschulz2/sf-housing-app/assets/29467201/8b7bff7f-8319-407e-b2fb-db37e5c852a3

**Comment by VCasecnikovs** [comment] 2023-11-14 03:06
Works in Safari, Does not work in ARC

**Comment by neallseth** [comment] 2023-11-14 04:14
Appreciate the report! We're aware of this and will be looking into a fix -- in the meanwhile, do let us know if you have clues as to the cause.

**Comment by neallseth** [comment] 2024-06-24 22:47
Should be resolved as of earlier this year - let me know if not, but closing for now!

**Closed as completed by neallseth** 2024-06-24 22:47 UTC
Labels: bug
